api.treasury:
  base-url: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service"

logging.level:
  root: "INFO"
  org:
    springframework: "WARN"
    hibernate: "WARN"
  com.zaxxer.hikari: "WARN"

management:
  endpoint:
    health:
      group:
        liveness.include: "livenessState"
        readiness.include: "readinessState,db,treasuryApi"
      show-details: "ALWAYS"
  endpoints:
    web.exposure.include: "health,info,prometheus,loggers"
  health:
    probes.enabled: "true"
  server.port: 4444
  tracing.sampling.probability: 1


server.shutdown: "graceful"

spring:
  cache:
    cache-name: "exchange-rate-cache"
    caffeine.spec: "recordStats,maximumSize=5000,expireAfterAccess=60m"
  jpa:
    open-in-view: false
    hibernate.ddl-auto: "update"
  threads.virtual.enabled: "true"
